theme = "nord-dark"
icons = "awesome6"

[[block]]
block = "music"
format = "$combo.str(20) $play $next|"
player = "spotify"


[[block]]
block = "custom"
command = "whoami"
interval = "once"

[[block]]
block = "net"
device = "wlo1"
format = "{$signal_strength $ssid}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "$available.eng(2)"
 
[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_total_used_percents.eng(2)"
format_swap = "$swap_used_percents.eng(2)"

# [[block]]
# block = "cpu"

#[[block]]
#block = "load"
#interval = 5

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "weather"
format = "$weather ($location) $temp"
service = { name = "openweathermap", api_key = "c5308a4ad56ce3ba4f7bf96e330c05ff", city_id = "3446130", units = "metric" }

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "battery"
format = "$percentage $time"
full_format = ""

# [[block]]
# block = "bluetooth"
# mac = "DC:2C:26:33:F4:7D"
# hide_disconnected = true
# format = "$name{ $percentage|}|Unavailable"
